In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)  

array([[19, 22],
       [43, 50]])

In [5]:
np.transpose(B)

array([[5, 7],
       [6, 8]])

In [7]:
result = np.linalg.det(A)
print(result)

-2.0000000000000004


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))
print(concatenated)

[1 2 3 4 5 6]


In [11]:
arr_vstack = np.vstack((arr1, arr2))
print(arr_vstack)

[[1 2 3]
 [4 5 6]]


In [13]:
arr_add=arr1+arr2
print(arr_add)

[5 7 9]


In [15]:
arr_multiply=arr1*arr2
print(arr_multiply)

[ 4 10 18]


In [17]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.95177717 0.8946821  0.74457462]
 [0.22876861 0.13788324 0.11439946]
 [0.1029942  0.33140229 0.69435231]]


In [21]:
inverse=np.linalg.inv(random_array)
print(inverse)

[[-1.88603841e+00  1.22133719e+01  1.02156192e-02]
 [ 4.79647921e+00 -1.90530977e+01 -2.00427454e+00]
 [-2.00951757e+00  7.28208671e+00  2.39528117e+00]]


In [23]:
def square (x):
    return x**2

res = square(5)
print(res)

25


In [25]:
def numerical_derivative(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

res = numerical_derivative(square, 5)
print(res)

9.999999999621423


In [27]:
angle_deg = 60
angle_rad = np.deg2rad(angle_deg)

sin_val = np.sin(angle_rad)
cos_val = np.cos(angle_rad)

print(f"Sinus is {sin_val}")
print(f"Cosinus is {cos_val}")

Sinus is 0.8660254037844386
Cosinus is 0.5000000000000001


In [34]:
def f(x):
    return x**2
x = np.linspace(-5, 5, 100)
gradient = np.gradient(f(x))
print(gradient)

[-0.99989797 -0.98969493 -0.96928885 -0.94888277 -0.92847669 -0.90807061
 -0.88766452 -0.86725844 -0.84685236 -0.82644628 -0.8060402  -0.78563412
 -0.76522804 -0.74482196 -0.72441588 -0.70400979 -0.68360371 -0.66319763
 -0.64279155 -0.62238547 -0.60197939 -0.58157331 -0.56116723 -0.54076115
 -0.52035507 -0.49994898 -0.4795429  -0.45913682 -0.43873074 -0.41832466
 -0.39791858 -0.3775125  -0.35710642 -0.33670034 -0.31629426 -0.29588817
 -0.27548209 -0.25507601 -0.23466993 -0.21426385 -0.19385777 -0.17345169
 -0.15304561 -0.13263953 -0.11223345 -0.09182736 -0.07142128 -0.0510152
 -0.03060912 -0.01020304  0.01020304  0.03060912  0.0510152   0.07142128
  0.09182736  0.11223345  0.13263953  0.15304561  0.17345169  0.19385777
  0.21426385  0.23466993  0.25507601  0.27548209  0.29588817  0.31629426
  0.33670034  0.35710642  0.3775125   0.39791858  0.41832466  0.43873074
  0.45913682  0.4795429   0.49994898  0.52035507  0.54076115  0.56116723
  0.58157331  0.60197939  0.62238547  0.64279155  0.

In [36]:
data = np.random.randn(1000)
np.mean(data)

-0.05249542852318199